# Generated by Django 5.2.1 on 2025-07-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("doctors", "0002_initial"),
        ("patients", "0002_patientspecialtyaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_complaint", models.TextField()),
                ("case_history", models.TextField()),
                ("vital_signs", models.JSONField()),
                ("recommendations", models.TextField()),
                ("cost", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="patients.patient",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="archives_ar_created_d7ebc4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "doctor", "appointment", "specialty"),
                        name="unique_archives_archive_patient_doctor_appointment_specialty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArchiveAccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_access_permissions",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_access_permissions",
                        to="patients.patient",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_access_permissions",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "db_table": "archives_archive_access_permission",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="archives_ar_created_a3f335_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "doctor", "specialty"),
                        name="unique_archives_archive_access_permission_patient_id_doctor_id_specialty_id",
                    )
                ],
            },
        ),
    ]
