# Generated by Django 5.2.1 on 2025-08-14 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("archives", "0001_initial"),
        ("doctors", "0002_initial"),
        ("patients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archives",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AddField(
            model_name="archiveaccesspermission",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_access_permissions",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="archiveaccesspermission",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_access_permissions",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="archiveaccesspermission",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_access_permissions",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="appointments.appointment",
                verbose_name="Appointment",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchiveaccesspermission",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchiveaccesspermission",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalarchiveaccesspermission",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="historicalarchiveaccesspermission",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["-created_at"], name="archives_ar_created_d7ebc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["-updated_at"], name="archives_ar_updated_5d4cd4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="archive",
            constraint=models.UniqueConstraint(
                fields=("patient", "doctor", "appointment", "specialty"),
                name="unique_archives_archive_patient_doctor_appointment_specialty",
            ),
        ),
        migrations.AddIndex(
            model_name="archiveaccesspermission",
            index=models.Index(
                fields=["created_at"], name="archives_ar_created_a3f335_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="archiveaccesspermission",
            constraint=models.UniqueConstraint(
                fields=("patient", "doctor", "specialty"),
                name="unique_archives_archive_access_permission_patient_id_doctor_id_specialty_id",
            ),
        ),
    ]
