# Generated by Django 5.2.1 on 2025-07-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="vital_signs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
