# Generated by Django 5.2.1 on 2025-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="paid",
            field=models.FloatField(default=0.0, verbose_name="Paid"),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="paid",
            field=models.FloatField(default=0.0, verbose_name="Paid"),
        ),
    ]
