# Generated by Django 5.2.1 on 2025-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("archives", "0002_alter_archive_recommendations_and_more"),
        ("doctors", "0002_initial"),
        ("patients", "0002_patientspecialtyaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["-updated_at"], name="archives_ar_updated_5d4cd4_idx"
            ),
        ),
    ]
