# Generated by Django 5.2.1 on 2025-08-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0003_alter_appointment_options_alter_attachment_options_and_more",
        ),
        ("archives", "0002_initial"),
        ("doctors", "0003_alter_achievement_options_alter_doctor_options_and_more"),
        ("patients", "0003_alter_historicalpatient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archive",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Archive",
                "verbose_name_plural": "Archives",
            },
        ),
        migrations.AlterModelOptions(
            name="archiveaccesspermission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Archive Access Permission",
                "verbose_name_plural": "Archive Access Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalarchive",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Archive",
                "verbose_name_plural": "historical Archives",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalarchiveaccesspermission",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Archive Access Permission",
                "verbose_name_plural": "historical Archive Access Permissions",
            },
        ),
        migrations.AlterField(
            model_name="archive",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="appointments.appointment",
                verbose_name="Appointment",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="case_history",
            field=models.TextField(verbose_name="Case History"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="cost",
            field=models.FloatField(verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="main_complaint",
            field=models.TextField(verbose_name="Main Complaint"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archives",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="recommendations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recommendations"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="vital_signs",
            field=models.JSONField(blank=True, null=True, verbose_name="Vital Signs"),
        ),
        migrations.AlterField(
            model_name="archiveaccesspermission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="archiveaccesspermission",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_access_permissions",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="archiveaccesspermission",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_access_permissions",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="archiveaccesspermission",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_access_permissions",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="appointments.appointment",
                verbose_name="Appointment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="case_history",
            field=models.TextField(verbose_name="Case History"),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="cost",
            field=models.FloatField(verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="main_complaint",
            field=models.TextField(verbose_name="Main Complaint"),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="recommendations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recommendations"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchive",
            name="vital_signs",
            field=models.JSONField(blank=True, null=True, verbose_name="Vital Signs"),
        ),
        migrations.AlterField(
            model_name="historicalarchiveaccesspermission",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchiveaccesspermission",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchiveaccesspermission",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarchiveaccesspermission",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
    ]
