# Generated by Django 5.2.1 on 2025-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcustomuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical User",
                "verbose_name_plural": "historical Users",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/users/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff Status"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified_email",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified_phone",
            field=models.BooleanField(default=False, verbose_name="Phone Verified"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Login"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("assistant", "Assistant"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=10,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="image",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff Status"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_verified_email",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_verified_phone",
            field=models.BooleanField(default=False, verbose_name="Phone Verified"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Login"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="phone",
            field=models.CharField(db_index=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("assistant", "Assistant"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=10,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
    ]
