# Generated by Django 5.2.1 on 2025-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_verified_phone",
            field=models.BooleanField(default=False),
        ),
    ]
