# Generated by Django 5.2.1 on 2025-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
