# Generated by Django 5.2.1 on 2025-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/%Y/%m/%d/"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["-created_at"], name="users_custo_created_5ef373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["-updated_at"], name="users_custo_updated_9cfb63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["-birth_date"], name="users_custo_birth_d_666306_idx"
            ),
        ),
    ]
