# Generated by Django 5.2.1 on 2025-05-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_options_alter_customuser_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_verified_phone",
            field=models.BooleanField(default=True),
        ),
    ]
