# Generated by Django 5.2.1 on 2025-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_birth_date_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("assistant", "Assistant"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
    ]
