# Generated by Django 5.2.1 on 2025-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/clinics/%Y/%m/%d/"
            ),
        ),
    ]
