# Generated by Django 5.2.1 on 2025-07-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_trigram_ext"),
        ("patients", "0003_patientspecialtyaccess_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinics",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="clinics_cli_created_3e6b16_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="clinics_cli_updated_09bb1a_idx"
                    ),
                ],
            },
        ),
    ]
