# Generated by Django 5.2.1 on 2025-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_alter_clinicimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="time_slot_per_patient",
            field=models.PositiveIntegerField(
                default=15, help_text="Length of each appointment slot in minutes"
            ),
        ),
    ]
