# Generated by Django 5.2.1 on 2025-06-18 15:07

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
