# Generated by Django 5.2.1 on 2025-07-17 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_clinic_time_slot_per_patient"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banned_patients",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banned_from",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("clinic", "patient")},
            },
        ),
    ]
