# Generated by Django 5.2.1 on 2025-08-11 19:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_trigram_ext"),
        ("doctors", "0003_alter_achievement_options_alter_doctor_options_and_more"),
        ("patients", "0003_alter_historicalpatient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bannedpatient",
            options={
                "verbose_name": "Banned Patient",
                "verbose_name_plural": "Banned Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="clinic",
            options={"verbose_name": "Clinic", "verbose_name_plural": "Clinics"},
        ),
        migrations.AlterModelOptions(
            name="clinicimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Clinic Image",
                "verbose_name_plural": "Clinic Images",
            },
        ),
        migrations.AlterModelOptions(
            name="clinicpatient",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Clinic Patient",
                "verbose_name_plural": "Clinic Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbannedpatient",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Banned Patient",
                "verbose_name_plural": "historical Banned Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalclinic",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Clinic",
                "verbose_name_plural": "historical Clinics",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalclinicimage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Clinic Image",
                "verbose_name_plural": "historical Clinic Images",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalclinicpatient",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Clinic Patient",
                "verbose_name_plural": "historical Clinic Patients",
            },
        ),
        migrations.AlterField(
            model_name="bannedpatient",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banned_patients",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="bannedpatient",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="bannedpatient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banned_from",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="doctor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="clinic",
                serialize=False,
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="time_slot_per_patient",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Length of each appointment slot in minutes",
                verbose_name="Time Slot Per Patient",
            ),
        ),
        migrations.AlterField(
            model_name="clinicimage",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="clinicimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="clinicimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/clinics/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="clinicimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="clinicpatient",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinics",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="clinicpatient",
            name="cost",
            field=models.FloatField(verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="clinicpatient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="clinicpatient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="clinicpatient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="historicalbannedpatient",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbannedpatient",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbannedpatient",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinic",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="historicalclinic",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinic",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinic",
            name="phone",
            field=models.CharField(db_index=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="historicalclinic",
            name="time_slot_per_patient",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Length of each appointment slot in minutes",
                verbose_name="Time Slot Per Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicimage",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicimage",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicimage",
            name="image",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicimage",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicpatient",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicpatient",
            name="cost",
            field=models.FloatField(verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="historicalclinicpatient",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicpatient",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicpatient",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
    ]
