# Generated by Django 5.2.1 on 2025-07-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_clinicpatient"),
        ("clinics", "0004_bannedpatient"),
    ]

    operations = []
