# Generated by Django 5.2.1 on 2025-08-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0005_merge_0003_clinicpatient_0004_bannedpatient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClinicPatient",
        ),
    ]
