# Generated by Django 5.2.1 on 2025-08-14 17:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="assistant",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "joined_clinic_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joined Clinic At"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="About"),
                ),
                ("education", models.TextField(verbose_name="Education")),
                ("start_work_date", models.DateField(verbose_name="Start Work Date")),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="clinics.clinic",
                        verbose_name="Clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant",
                "verbose_name_plural": "Assistants",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAssistant",
            fields=[
                (
                    "joined_clinic_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joined Clinic At"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="About"),
                ),
                ("education", models.TextField(verbose_name="Education")),
                ("start_work_date", models.DateField(verbose_name="Start Work Date")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinic",
                        verbose_name="Clinic",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Assistant",
                "verbose_name_plural": "historical Assistants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
