# Generated by Django 5.2.1 on 2025-05-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("users", "0010_customuser_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="assistant",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("about", models.TextField()),
                ("education", models.TextField()),
                ("start_work_date", models.DateField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="clinics.clinic",
                    ),
                ),
            ],
        ),
    ]
