# Generated by Django 5.2.1 on 2025-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="about",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="start_work_date",
            field=models.DateField(),
        ),
    ]
