# Generated by Django 5.2.1 on 2025-08-11 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0001_initial"),
        ("clinics", "0004_alter_bannedpatient_options_alter_clinic_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assistant",
            options={"verbose_name": "Assistant", "verbose_name_plural": "Assistants"},
        ),
        migrations.AlterModelOptions(
            name="historicalassistant",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Assistant",
                "verbose_name_plural": "historical Assistants",
            },
        ),
        migrations.AlterField(
            model_name="assistant",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistants",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="education",
            field=models.TextField(verbose_name="Education"),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="joined_clinic_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Joined Clinic At"
            ),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="start_work_date",
            field=models.DateField(verbose_name="Start Work Date"),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="assistant",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassistant",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="historicalassistant",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassistant",
            name="education",
            field=models.TextField(verbose_name="Education"),
        ),
        migrations.AlterField(
            model_name="historicalassistant",
            name="joined_clinic_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Joined Clinic At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassistant",
            name="start_work_date",
            field=models.DateField(verbose_name="Start Work Date"),
        ),
        migrations.AlterField(
            model_name="historicalassistant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
