# Generated by Django 5.2.1 on 2025-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0002_alter_assistant_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
