# Generated by Django 5.2.1 on 2025-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0003_alter_assistant_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="joined_clinic",
            field=models.DateField(blank=True, null=True),
        ),
    ]
