# Generated by Django 5.2.1 on 2025-06-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0004_assistant_joined_clinic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assistant",
            old_name="joined_clinic",
            new_name="joined_clinic_at",
        ),
    ]
