# Generated by Django 5.2.1 on 2025-08-14 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_initial"),
        ("financials", "0001_initial"),
        ("patients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financials",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="financial",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financials",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="historicalfinancial",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="historicalfinancial",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfinancial",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="financial",
            index=models.Index(
                fields=["-created_at"], name="financials__created_dcf613_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financial",
            index=models.Index(
                fields=["-updated_at"], name="financials__updated_02338f_idx"
            ),
        ),
    ]
