# Generated by Django 5.2.1 on 2025-08-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_trigram_ext"),
        ("financials", "0002_initial"),
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Financial",
                "verbose_name_plural": "Financials",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfinancial",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Financial",
                "verbose_name_plural": "historical Financials",
            },
        ),
        migrations.AlterField(
            model_name="financial",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financials",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="financial",
            name="cost",
            field=models.FloatField(verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="financial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="financial",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financials",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="financial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="historicalfinancial",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfinancial",
            name="cost",
            field=models.FloatField(verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="historicalfinancial",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalfinancial",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfinancial",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
    ]
