# Generated by Django 5.2.1 on 2025-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancelled", "Cancelled"),
                    ("waiting", "Waiting"),
                    ("in_consultation", "In Consultation"),
                    ("completed", "Completed"),
                    ("absent", "Absent"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
