# Generated by Django 5.2.1 on 2025-08-11 19:04

import appointments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        ("clinics", "0004_alter_bannedpatient_options_alter_clinic_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalappointment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Appointment",
                "verbose_name_plural": "historical Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalattachment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Attachment",
                "verbose_name_plural": "historical Attachments",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="actual_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Actual End Time"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="actual_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Actual Start Time"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled At"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancelled By",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Patient who booked the appointment",
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancelled", "Cancelled"),
                    ("waiting", "Waiting"),
                    ("in_consultation", "In Consultation"),
                    ("completed", "Completed"),
                    ("absent", "Absent"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="visit_date",
            field=models.DateField(verbose_name="Visit Date"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="visit_time",
            field=models.TimeField(verbose_name="Visit Time"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="appointments.appointment",
                verbose_name="Appointment",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="document",
            field=models.FileField(
                upload_to=appointments.models.appointment_attachment_path,
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="actual_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Actual End Time"
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="actual_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Actual Start Time"
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancelled By",
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Patient who booked the appointment",
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancelled", "Cancelled"),
                    ("waiting", "Waiting"),
                    ("in_consultation", "In Consultation"),
                    ("completed", "Completed"),
                    ("absent", "Absent"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="visit_date",
            field=models.DateField(verbose_name="Visit Date"),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="visit_time",
            field=models.TimeField(verbose_name="Visit Time"),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="appointments.appointment",
                verbose_name="Appointment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="document",
            field=models.TextField(max_length=100, verbose_name="Document"),
        ),
    ]
