# Generated by Django 5.2.1 on 2025-06-26 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_notes_alter_appointment_status"),
        ("clinics", "0003_clinic_time_slot_per_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_clinic_visit_datetime",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("clinic", "visit_date", "visit_time"),
                name="unique_clinic_visit_datetime_if_not_cancelled",
            ),
        ),
    ]
