from django.urls import path

from . import views

urlpatterns = [
    path(
        "",
        views.UserCreateDestroyView.as_view(),
        name="user-create-destroy",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "refresh-token/",
        views.CustomTokenRefreshView.as_view(),
        name="refresh-token",
    ),
    path(
        "change-password/",
        views.ChangePasswordView.as_view(),
        name="change-password",
    ),
    path(
        "images/",
        views.ImageView.as_view(),
        name="user-image",
    ),
    path(
        "otp/signup/send/",
        views.SendSignUpOTPView.as_view(),
        name="otp-signup-send",
    ),
    path(
        "otp/signup/verify/",
        views.VerifySignUpOTPView.as_view(),
        name="otp-signup-verify",
    ),
    path(
        "otp/change-phone/send/",
        views.SendChangePhoneOTPView.as_view(),
        name="otp-change-phone-send",
    ),
    path(
        "otp/change-phone/verify/",
        views.VerifyChangePhoneOTPView.as_view(),
        name="otp-change-phone-verify",
    ),
    path(
        "forget-password/send-otp/",
        views.ForgetPasswordOTPSendView.as_view(),
        name="forget-password-send-otp",
    ),
    path(
        "forget-password/verify-otp/",
        views.ForgetPasswordOTPVerificationView.as_view(),
        name="forget-password-verify-otp",
    ),
    path(
        "forget-password/add-new-password/",
        views.AddNewPasswordView.as_view(),
        name="forget-password-add-otp",
    ),
]
