# Generated by Django 5.2.1 on 2025-06-18 15:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patient",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("job", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("medical_history", models.TextField(blank=True)),
                ("surgical_history", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("medicines", models.TextField(blank=True)),
                ("is_smoker", models.BooleanField(default=False)),
                ("is_drinker", models.BooleanField(default=False)),
                ("is_married", models.BooleanField(default=False)),
            ],
        ),
    ]
