# Generated by Django 5.2.1 on 2025-05-15 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_alter_customuser_is_verified_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("job", models.CharField(max_length=255)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("medical_history", models.TextField(blank=True)),
                ("surgical_history", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("medicines", models.TextField(blank=True)),
                ("is_smoker", models.BooleanField(default=False)),
                ("is_drinker", models.BooleanField(default=False)),
                ("is_married", models.BooleanField(default=False)),
            ],
        ),
    ]
