# Generated by Django 5.2.1 on 2025-08-09 18:36

import django.contrib.gis.db.models.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalPatient",
            fields=[
                ("address", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("job", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("medical_history", models.TextField(blank=True)),
                ("surgical_history", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("medicines", models.TextField(blank=True)),
                ("is_smoker", models.BooleanField(default=False)),
                ("is_drinker", models.BooleanField(default=False)),
                ("is_married", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient",
                "verbose_name_plural": "historical patients",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPatientSpecialtyAccess",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("restricted", "Restricted")],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient specialty access",
                "verbose_name_plural": "historical patient specialty accesss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
