# Generated by Django 5.2.1 on 2025-08-14 17:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0002_initial"),
        ("patients", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patient",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Location"
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Job"
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Blood Type",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, verbose_name="Medical History"),
                ),
                (
                    "surgical_history",
                    models.TextField(blank=True, verbose_name="Surgical History"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Allergies")),
                ("medicines", models.TextField(blank=True, verbose_name="Medicines")),
                (
                    "is_smoker",
                    models.BooleanField(default=False, verbose_name="Smoker"),
                ),
                (
                    "is_drinker",
                    models.BooleanField(default=False, verbose_name="Drinker"),
                ),
                (
                    "is_married",
                    models.BooleanField(default=False, verbose_name="Married"),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientspecialtyaccess",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientspecialtyaccess",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientspecialtyaccess",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.CreateModel(
            name="PatientSpecialtyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("restricted", "Restricted")],
                        max_length=15,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_specialty_accesses",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_specialty_accesses",
                        to="doctors.specialty",
                        verbose_name="Specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Specialty Access",
                "verbose_name_plural": "Patient Specialty Accesses",
                "db_table": "patients_patient_specialty_access",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="patients_pa_created_88cd3f_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="patients_pa_updated_f945fe_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "specialty"),
                        name="unique_patients_patient_specialty_access_patient_id_specialty_id",
                    )
                ],
            },
        ),
    ]
