# Generated by Django 5.2.1 on 2025-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
