# Generated by Django 5.2.1 on 2025-07-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSpecialtyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("restricted", "Restricted")],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_specialty_accesses",
                        to="patients.patient",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_specialty_accesses",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "db_table": "patients_patient_specialty_access",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="patients_pa_created_88cd3f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "specialty"),
                        name="unique_patients_patient_specialty_access_patient_id_specialty_id",
                    )
                ],
            },
        ),
    ]
