# Generated by Django 5.2.1 on 2025-08-09 18:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0002_initial"),
        ("patients", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patient",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("job", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("medical_history", models.TextField(blank=True)),
                ("surgical_history", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("medicines", models.TextField(blank=True)),
                ("is_smoker", models.BooleanField(default=False)),
                ("is_drinker", models.BooleanField(default=False)),
                ("is_married", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientspecialtyaccess",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientspecialtyaccess",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatientspecialtyaccess",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="PatientSpecialtyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("restricted", "Restricted")],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_specialty_accesses",
                        to="patients.patient",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_specialty_accesses",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "db_table": "patients_patient_specialty_access",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="patients_pa_created_88cd3f_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="patients_pa_updated_f945fe_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "specialty"),
                        name="unique_patients_patient_specialty_access_patient_id_specialty_id",
                    )
                ],
            },
        ),
    ]
