# Generated by Django 5.2.1 on 2025-08-11 19:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_achievement_options_alter_doctor_options_and_more"),
        ("patients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpatient",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Patient",
                "verbose_name_plural": "historical Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpatientspecialtyaccess",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Patient Specialty Access",
                "verbose_name_plural": "historical Patient Specialty Accesses",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.AlterModelOptions(
            name="patientspecialtyaccess",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Patient Specialty Access",
                "verbose_name_plural": "Patient Specialty Accesses",
            },
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="allergies",
            field=models.TextField(blank=True, verbose_name="Allergies"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
                verbose_name="Blood Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="is_drinker",
            field=models.BooleanField(default=False, verbose_name="Drinker"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="is_married",
            field=models.BooleanField(default=False, verbose_name="Married"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="is_smoker",
            field=models.BooleanField(default=False, verbose_name="Smoker"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="job",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Job"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="medical_history",
            field=models.TextField(blank=True, verbose_name="Medical History"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="medicines",
            field=models.TextField(blank=True, verbose_name="Medicines"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="surgical_history",
            field=models.TextField(blank=True, verbose_name="Surgical History"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientspecialtyaccess",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientspecialtyaccess",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientspecialtyaccess",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientspecialtyaccess",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientspecialtyaccess",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("restricted", "Restricted")],
                max_length=15,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, verbose_name="Allergies"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
                verbose_name="Blood Type",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="is_drinker",
            field=models.BooleanField(default=False, verbose_name="Drinker"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="is_married",
            field=models.BooleanField(default=False, verbose_name="Married"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="is_smoker",
            field=models.BooleanField(default=False, verbose_name="Smoker"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="job",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Job"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, verbose_name="Medical History"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medicines",
            field=models.TextField(blank=True, verbose_name="Medicines"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="surgical_history",
            field=models.TextField(blank=True, verbose_name="Surgical History"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="patient",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="patientspecialtyaccess",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="patientspecialtyaccess",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_specialty_accesses",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="patientspecialtyaccess",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_specialty_accesses",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="patientspecialtyaccess",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="patientspecialtyaccess",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("restricted", "Restricted")],
                max_length=15,
                verbose_name="Visibility",
            ),
        ),
    ]
