# Generated by Django 5.2.1 on 2025-07-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        ("patients", "0002_patientspecialtyaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientspecialtyaccess",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="patientspecialtyaccess",
            index=models.Index(
                fields=["-updated_at"], name="patients_pa_updated_f945fe_idx"
            ),
        ),
    ]
