# Generated by Django 5.2.1 on 2025-05-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="id",
            new_name="user",
        ),
    ]
