# Generated by Django 5.2.1 on 2025-05-16 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0009_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="doctor",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("description", models.TextField()),
                ("education", models.TextField()),
                ("start_work_date", models.DateField(blank=True, null=True)),
                ("certificate", models.FileField(upload_to="documents/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["start_work_date"],
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="clinic",
                        serialize=False,
                        to="doctors.doctor",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("phone", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_specialties",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "specialty",
                "verbose_name_plural": "specialties",
            },
        ),
        migrations.CreateModel(
            name="DoctorSpecialty",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "doctor_id",
                        "specialty_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("university", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Specialty",
                "verbose_name_plural": "Doctor Specialties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                related_name="doctors",
                through="doctors.DoctorSpecialty",
                to="doctors.specialty",
            ),
        ),
        migrations.CreateModel(
            name="ClinicImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="doctors.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="doctors_ach_created_188942_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="doctors_ach_updated_250f9b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="doctorspecialty",
            index=models.Index(
                fields=["-created_at"], name="doctors_doc_created_882685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorspecialty",
            index=models.Index(
                fields=["-updated_at"], name="doctors_doc_updated_07d64a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["start_work_date"], name="doctors_doc_start_w_b153fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicimage",
            index=models.Index(
                fields=["-created_at"], name="doctors_cli_created_b9b8f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicimage",
            index=models.Index(
                fields=["-updated_at"], name="doctors_cli_updated_7cbd3b_idx"
            ),
        ),
    ]
