# Generated by Django 5.2.1 on 2025-08-09 18:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="doctor",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("about", models.TextField()),
                ("education", models.TextField()),
                ("start_work_date", models.DateField(blank=True, null=True)),
                (
                    "certificate",
                    models.FileField(upload_to="documents/certificates/%Y/%m/%d/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("declined", "Declined"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("rate", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["start_work_date"],
            },
        ),
        migrations.CreateModel(
            name="MainSpecialtySubspecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Main Specialty Subspecialty",
                "verbose_name_plural": "Main Specialty Subspecialties",
                "db_table": "doctors_main_specialty_subspecialty",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="achievement",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="doctors.doctor",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAchievement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical achievement",
                "verbose_name_plural": "historical achievements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDoctor",
            fields=[
                ("about", models.TextField()),
                ("education", models.TextField()),
                ("start_work_date", models.DateField(blank=True, null=True)),
                ("certificate", models.TextField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("declined", "Declined"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("rate", models.FloatField(default=0.0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical doctor",
                "verbose_name_plural": "historical doctors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSpecialty",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_ar", models.CharField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical specialty",
                "verbose_name_plural": "historical specialties",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_ar", models.CharField(max_length=100)),
                (
                    "subspecialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="main_specialties",
                        through="doctors.MainSpecialtySubspecialty",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "specialty",
                "verbose_name_plural": "specialties",
            },
        ),
        migrations.AddField(
            model_name="mainspecialtysubspecialty",
            name="main_specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subspecialty_relations",
                to="doctors.specialty",
                verbose_name="Main Specialty",
            ),
        ),
        migrations.AddField(
            model_name="mainspecialtysubspecialty",
            name="subspecialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_specialty_relations",
                to="doctors.specialty",
                verbose_name="Subspecialty",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalMainSpecialtySubspecialty",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_specialty",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="doctors.specialty",
                        verbose_name="Main Specialty",
                    ),
                ),
                (
                    "subspecialty",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="doctors.specialty",
                        verbose_name="Subspecialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Main Specialty Subspecialty",
                "verbose_name_plural": "historical Main Specialty Subspecialties",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDoctorSpecialty",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("university", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Doctor Specialty",
                "verbose_name_plural": "historical Doctor Specialties",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DoctorSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_specialties",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Specialty",
                "verbose_name_plural": "Doctor Specialties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                related_name="doctors",
                through="doctors.DoctorSpecialty",
                to="doctors.specialty",
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["-created_at"], name="doctors_ach_created_188942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["-updated_at"], name="doctors_ach_updated_250f9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialty",
            constraint=models.UniqueConstraint(
                fields=("name_en", "name_ar"), name="unique_name"
            ),
        ),
        migrations.AddIndex(
            model_name="mainspecialtysubspecialty",
            index=models.Index(
                fields=["-created_at"], name="doctors_mai_created_6bc0c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mainspecialtysubspecialty",
            index=models.Index(
                fields=["-updated_at"], name="doctors_mai_updated_09722e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mainspecialtysubspecialty",
            constraint=models.UniqueConstraint(
                fields=("main_specialty", "subspecialty"),
                name="unique_main_subspecialty",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorspecialty",
            index=models.Index(
                fields=["-created_at"], name="doctors_doc_created_882685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorspecialty",
            index=models.Index(
                fields=["-updated_at"], name="doctors_doc_updated_07d64a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorspecialty",
            constraint=models.UniqueConstraint(
                fields=("doctor", "specialty"), name="unique_doctor_specialty"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["start_work_date"], name="doctors_doc_start_w_b153fa_idx"
            ),
        ),
    ]
