# Generated by Django 5.2.1 on 2025-06-18 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="doctor",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("about", models.TextField()),
                ("education", models.TextField()),
                ("start_work_date", models.DateField(blank=True, null=True)),
                (
                    "certificate",
                    models.FileField(upload_to="documents/certificates/%Y/%m/%d/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("declined", "Declined"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["start_work_date"],
            },
        ),
        migrations.AddField(
            model_name="achievement",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="doctors.doctor",
            ),
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_ar", models.CharField(max_length=100)),
                (
                    "subspecialties",
                    models.ManyToManyField(
                        blank=True,
                        db_table="doctors_main_specialty_subspecialty",
                        related_name="main_specialties",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "specialty",
                "verbose_name_plural": "specialties",
            },
        ),
        migrations.CreateModel(
            name="DoctorSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_specialties",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Specialty",
                "verbose_name_plural": "Doctor Specialties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                related_name="doctors",
                through="doctors.DoctorSpecialty",
                to="doctors.specialty",
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["-created_at"], name="doctors_ach_created_188942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["-updated_at"], name="doctors_ach_updated_250f9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialty",
            constraint=models.UniqueConstraint(
                fields=("name_en", "name_ar"), name="unique_name"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorspecialty",
            index=models.Index(
                fields=["-created_at"], name="doctors_doc_created_882685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorspecialty",
            index=models.Index(
                fields=["-updated_at"], name="doctors_doc_updated_07d64a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorspecialty",
            constraint=models.UniqueConstraint(
                fields=("doctor", "specialty"), name="unique_doctor_specialty"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["start_work_date"], name="doctors_doc_start_w_b153fa_idx"
            ),
        ),
    ]
