# Generated by Django 5.2.1 on 2025-05-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_doctorspecialty_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subspecialties",
                to="doctors.specialty",
            ),
        ),
    ]
