# Generated by Django 5.2.1 on 2025-05-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_specialty_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="description",
            new_name="about",
        ),
    ]
