# Generated by Django 5.2.1 on 2025-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="rate",
            field=models.FloatField(default=0.0),
        ),
    ]
