# Generated by Django 5.2.1 on 2025-08-11 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["start_work_date"],
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalachievement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Achievement",
                "verbose_name_plural": "historical Achievements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldoctor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Doctor",
                "verbose_name_plural": "historical Doctors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalspecialty",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Specialty",
                "verbose_name_plural": "historical Specialties",
            },
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={"verbose_name": "Specialty", "verbose_name_plural": "Specialties"},
        ),
        migrations.AlterField(
            model_name="achievement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="about",
            field=models.TextField(verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="certificate",
            field=models.FileField(
                upload_to="documents/certificates/%Y/%m/%d/", verbose_name="Certificate"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="education",
            field=models.TextField(verbose_name="Education"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="rate",
            field=models.FloatField(default=0.0, verbose_name="Rate"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                related_name="doctors",
                through="doctors.DoctorSpecialty",
                to="doctors.specialty",
                verbose_name="Specialties",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="start_work_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start Work Date"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("declined", "Declined"),
                ],
                default="approved",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="doctor",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="doctorspecialty",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="doctorspecialty",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_specialties",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="doctorspecialty",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="doctorspecialty",
            name="university",
            field=models.CharField(max_length=150, verbose_name="University"),
        ),
        migrations.AlterField(
            model_name="doctorspecialty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="historicalachievement",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalachievement",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="historicalachievement",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalachievement",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalachievement",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="about",
            field=models.TextField(verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="certificate",
            field=models.TextField(max_length=100, verbose_name="Certificate"),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="education",
            field=models.TextField(verbose_name="Education"),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="rate",
            field=models.FloatField(default=0.0, verbose_name="Rate"),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="start_work_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start Work Date"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("declined", "Declined"),
                ],
                default="approved",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctorspecialty",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctorspecialty",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.doctor",
                verbose_name="Doctor",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctorspecialty",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="doctors.specialty",
                verbose_name="Specialty",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctorspecialty",
            name="university",
            field=models.CharField(max_length=150, verbose_name="University"),
        ),
        migrations.AlterField(
            model_name="historicaldoctorspecialty",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmainspecialtysubspecialty",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmainspecialtysubspecialty",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalspecialty",
            name="name_ar",
            field=models.CharField(max_length=100, verbose_name="Name (Arabic)"),
        ),
        migrations.AlterField(
            model_name="historicalspecialty",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Name (English)"),
        ),
        migrations.AlterField(
            model_name="mainspecialtysubspecialty",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="mainspecialtysubspecialty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name_ar",
            field=models.CharField(max_length=100, verbose_name="Name (Arabic)"),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Name (English)"),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="subspecialties",
            field=models.ManyToManyField(
                blank=True,
                related_name="main_specialties",
                through="doctors.MainSpecialtySubspecialty",
                to="doctors.specialty",
                verbose_name="Subspecialties",
            ),
        ),
    ]
