# Generated by Django 5.2.1 on 2025-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="certificate",
            field=models.FileField(upload_to="documents/certificates/%Y/%m/%d/"),
        ),
    ]
