# Generated by Django 5.2.1 on 2025-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalspecialty",
            name="image",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="specialty",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="specialties/images/",
                verbose_name="Image",
            ),
        ),
    ]
