# Generated by Django 5.2.1 on 2025-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctor_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="specialties/images/"
            ),
        ),
    ]
