# Generated by Django 5.2.1 on 2025-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctor_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("declined", "Declined"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
