# Generated by Django 5.2.1 on 2025-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_historicalspecialty_image_specialty_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="rate",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=2, verbose_name="Rate"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="rate",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=2, verbose_name="Rate"
            ),
        ),
    ]
