# Generated by Django 5.2.1 on 2025-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctor_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialty",
            name="parent",
        ),
        migrations.AddField(
            model_name="specialty",
            name="subspecialties",
            field=models.ManyToManyField(
                blank=True,
                db_table="doctors_main_specialty_subspecialty",
                related_name="main_specialties",
                to="doctors.specialty",
            ),
        ),
    ]
