# Generated by Django 5.2.1 on 2025-06-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0003_clinic_time_slot_per_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_name",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "special_date",
                    models.DateField(
                        blank=True,
                        help_text="Overrides weekly schedule if set",
                        null=True,
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["clinic", "day_name"],
                        name="schedules_c_clinic__0c1401_idx",
                    ),
                    models.Index(
                        fields=["clinic", "special_date"],
                        name="schedules_c_clinic__e090c7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "day_name", "special_date"),
                        name="unique_clinic_schedule",
                    )
                ],
            },
        ),
    ]
