# Generated by Django 5.2.1 on 2025-06-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_hour", models.TimeField()),
                ("end_hour", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_hours",
                        to="schedules.clinicschedule",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["schedule", "start_hour", "end_hour"],
                        name="schedules_a_schedul_e5c481_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_hour__gt", models.F("start_hour"))),
                        name="check_start_before_end",
                    )
                ],
            },
        ),
    ]
