# Generated by Django 5.2.1 on 2025-08-14 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_initial"),
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicschedule",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AddField(
            model_name="availablehour",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_hours",
                to="schedules.clinicschedule",
                verbose_name="Schedule",
            ),
        ),
        migrations.AddField(
            model_name="historicalavailablehour",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalavailablehour",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="schedules.clinicschedule",
                verbose_name="Schedule",
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicschedule",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicschedule",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clinicschedule",
            index=models.Index(
                fields=["clinic", "day_name"], name="schedules_c_clinic__0c1401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicschedule",
            index=models.Index(
                fields=["clinic", "special_date"], name="schedules_c_clinic__e090c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicschedule",
            constraint=models.UniqueConstraint(
                fields=("clinic", "day_name", "special_date"),
                name="unique_clinic_schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="availablehour",
            index=models.Index(
                fields=["schedule", "start_hour", "end_hour"],
                name="schedules_a_schedul_e5c481_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="availablehour",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_hour__gt", models.F("start_hour"))),
                name="check_start_before_end",
            ),
        ),
    ]
