# Generated by Django 5.2.1 on 2025-08-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_alter_bannedpatient_options_alter_clinic_options_and_more"),
        ("schedules", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availablehour",
            options={
                "verbose_name": "Available Hour",
                "verbose_name_plural": "Available Hours",
            },
        ),
        migrations.AlterModelOptions(
            name="clinicschedule",
            options={
                "verbose_name": "Clinic Schedule",
                "verbose_name_plural": "Clinic Schedules",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalavailablehour",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Available Hour",
                "verbose_name_plural": "historical Available Hours",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalclinicschedule",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Clinic Schedule",
                "verbose_name_plural": "historical Clinic Schedules",
            },
        ),
        migrations.AlterField(
            model_name="availablehour",
            name="end_hour",
            field=models.TimeField(verbose_name="End Hour"),
        ),
        migrations.AlterField(
            model_name="availablehour",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_hours",
                to="schedules.clinicschedule",
                verbose_name="Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="availablehour",
            name="start_hour",
            field=models.TimeField(verbose_name="Start Hour"),
        ),
        migrations.AlterField(
            model_name="clinicschedule",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="clinicschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="clinicschedule",
            name="day_name",
            field=models.CharField(
                choices=[
                    ("sunday", "Sunday"),
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                ],
                default="special",
                max_length=9,
                verbose_name="Day Name",
            ),
        ),
        migrations.AlterField(
            model_name="clinicschedule",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="Is Available"),
        ),
        migrations.AlterField(
            model_name="clinicschedule",
            name="special_date",
            field=models.DateField(
                blank=True,
                help_text="Overrides weekly schedule if set",
                null=True,
                verbose_name="Special Date",
            ),
        ),
        migrations.AlterField(
            model_name="clinicschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="historicalavailablehour",
            name="end_hour",
            field=models.TimeField(verbose_name="End Hour"),
        ),
        migrations.AlterField(
            model_name="historicalavailablehour",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="schedules.clinicschedule",
                verbose_name="Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="historicalavailablehour",
            name="start_hour",
            field=models.TimeField(verbose_name="Start Hour"),
        ),
        migrations.AlterField(
            model_name="historicalclinicschedule",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicschedule",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicschedule",
            name="day_name",
            field=models.CharField(
                choices=[
                    ("sunday", "Sunday"),
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                ],
                default="special",
                max_length=9,
                verbose_name="Day Name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicschedule",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="Is Available"),
        ),
        migrations.AlterField(
            model_name="historicalclinicschedule",
            name="special_date",
            field=models.DateField(
                blank=True,
                help_text="Overrides weekly schedule if set",
                null=True,
                verbose_name="Special Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicschedule",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated At"
            ),
        ),
    ]
