# Generated by Django 5.2.1 on 2025-06-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_availablehour"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="availablehour",
            name="check_start_before_end",
        ),
    ]
