# Generated by Django 5.2.1 on 2025-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_remove_availablehour_check_start_before_end"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availablehour",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_hour__gt", models.F("start_hour"))),
                name="check_start_before_end",
            ),
        ),
    ]
