# Generated by Django 5.2.1 on 2025-06-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_availablehour_check_start_before_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availablehour",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="availablehour",
            name="updated_at",
        ),
    ]
