# Generated by Django 5.2.1 on 2025-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_remove_availablehour_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicschedule",
            name="day_name",
            field=models.CharField(
                choices=[
                    ("sunday", "Sunday"),
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                ],
                default="special",
                max_length=9,
            ),
        ),
    ]
