"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.core.management.utils import get_random_secret_key

from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", cast=str, default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "drf_spectacular_sidecar",  # required for Django collectstatic discovery
    "nested_admin",
    "file_validator",
    "django_filters",
    # project apps
    "users",
    "patients",
    "doctors",
    "clinics",
    "assistants",
    "schedules",
    "appointments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.{}".format(
            config("DATABASE_ENGINE", "postgresql")
        ),
        "NAME": config("DATABASE_NAME", "oxytocinDB"),
        "USER": config("DATABASE_USERNAME", "postgres"),
        "PASSWORD": config("DATABASE_PASSWORD", "12345678"),
        "HOST": config("DATABASE_HOST", "localhost"),
        "PORT": config("DATABASE_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "users.validators.UpperLowerCaseValidator",
    },
    {
        "NAME": "users.validators.DigitSymbolValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ar-sy"

TIME_ZONE = "Asia/Damascus"

USE_I18N = True

USE_TZ = True

# for translating error & messages:
LOCALE_PATHS = [
    BASE_DIR / "locale",  # or os.path.join(BASE_DIR, 'locale')
    BASE_DIR / "users/locale",
    BASE_DIR / "patients/locale",
    BASE_DIR / "doctors/locale",
    BASE_DIR / "clinics/locale",
    BASE_DIR / "assistants/locale",
    BASE_DIR / "schedules/locale",
    BASE_DIR / "appointments/locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Use Custom User:
AUTH_USER_MODEL = "users.CustomUser"

# CORS
CORS_ALLOW_ALL_ORIGINS = True

# Media
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# file-validator
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]
FILE_VALIDATOR_ERROR_MESSAGE = (
    "The file '{current_file_name}' (size {current_file_size}, "
    "type {current_file_type}/{current_file_extension}, MIME {current_file_mime}) is not supported. "
    "Accepted types: {acceptable_types}. "
    "Accepted MIME types: {acceptable_mimes}. "
    "Maximum file size: {max_file_size}."
)

# Testing
TESTING = config("DJANGO_TESTING", cast=bool, default=False)

anon_rate = "5/minute"
user_rate = "10/minute"
login_rate = "3/minute"
otp_daily_rate = "3/day"
otp_interval_rate = "1/15minute"

if TESTING:
    anon_rate = "400/minute"
    user_rate = "400/minute"
    login_rate = "400/minute"
    otp_daily_rate = "100/day"
    otp_interval_rate = "400/minute"

# DRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": anon_rate,
        "user": user_rate,
        "login": login_rate,
        "otp_daily": otp_daily_rate,
        "otp_interval": otp_interval_rate,
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "BLACKLIST_AFTER_ROTATION": True,
    "ROTATE_REFRESH_TOKENS": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_BLACKLIST_ENABLED": True,
}

# Spectacular
SPECTACULAR_SETTINGS = {
    "TITLE": "Oxytocin API",
    "DESCRIPTION": "All endpoints you need for doctor, patient and assistant!!",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    # OTHER SETTINGS
}

# Redis
REDIS_PASSWORD = config("REDIS_PASSWORD", "12345678")

# Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD,
        },
        "KEY_PREFIX": "default",
    },
    "otp": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD,
        },
        "KEY_PREFIX": "otp",
        "TIMEOUT": 300,
    },
}

# RabbitMQ
RABBITMQ_USER = config("RABBITMQ_USER", "guest")
RABBITMQ_PASS = config("RABBITMQ_PASS", "guest")

# Celery
CELERY_BROKER_URL = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@rabbitmq:5672//"
CELERY_RESULT_BACKEND = f"redis://:{REDIS_PASSWORD}@redis:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"


# Textbee
TEXTBEE_API_KEY = config("TEXTBEE_API_KEY")
TEXTBEE_DEVICE_ID = config("TEXTBEE_DEVICE_ID")


# Safe phone numbers
SAFE_PHONE_NUMBERS = config(
    "SAFE_PHONE_NUMBERS",
    cast=lambda v: [s for s in v.split(",")],
    default=[],
)
